batch_size: 256
cnn_model_dir: ./checkpoint/cnn.ckpt
data_dir: ./samples/dataset_GAN.mat
gpus: 1
input_dim: 3000
load_dir: ../checkpoint/gan/gan.ckpt
loss_self_alpha: 1.4
loss_self_lamda1: 0.5
loss_self_lamda2: 0.5
loss_self_lamda3: 1.0
max_epochs: 500
min_epochs: 0
optim_Adam_b1: 0.9
optim_Adam_b2: 0.999
optim_Adam_lr: 0.001
save_dir: ./checkpoint/gan/gan.ckpt
test: false
train: true
valid: 0.2
